language: cpp
compiler:
  - clang
  - gcc
os:
  - osx
  - linux
env:
  - CONFIG=Release
  - CONFIG=Debug
matrix:
  exclude:
  - os: osx
    compiler: gcc
cache:
  directories:
    $HOME/source
install:
  - pushd devtools
  - ./travis-install-dependencies.sh "${HOME}/osvr"
  - popd
script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - if [ $TRAVIS_OS_NAME = 'osx' ];   then cmake .. -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_PREFIX_PATH=${HOME}/osvr -DOVR_ROOT_DIR="${HOME}/source/${CONFIG}/ovr_sdk" -DCMAKE_OSX_ARCHITECTURES=x86_64; fi
  - if [ $TRAVIS_OS_NAME = 'linux' ]; then cmake .. -DCMAKE_BUILD_TYPE=${CONFIG} -DCMAKE_PREFIX_PATH=${HOME}/osvr -DOVR_ROOT_DIR="${HOME}/source/${CONFIG}/ovr_sdk"; fi
  - make -j2
sudo: false
addons:
  apt:
    sources:
    - boost-latest
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - libboost-thread1.55-dev
    - libboost-system1.55-dev
    - libboost-date-time1.55-dev
    - libboost-chrono1.55-dev
    - libboost-program-options1.55-dev
    - libboost-filesystem1.55-dev
    - libusb-1.0-0-dev
    - cmake-data
    - cmake
    - gcc-5
    - g++-5
    - clang-3.7
    - libudev1
    - libudev-dev
